import { X, ExternalLink } from "lucide-react";

export default function AboutModal({ onClose }) {
  return (
    // Backdrop — click outside to close
    <div
      className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/70 backdrop-blur-sm"
      onClick={onClose}
    >
      {/* Panel — stop click propagation so clicking inside doesn't close */}
      <div
        className="relative w-full max-w-lg bg-gray-900 border border-gray-700 rounded-2xl shadow-2xl overflow-hidden"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-gray-800">
          <span className="text-white font-bold text-base">About MarketLens</span>
          <button
            onClick={onClose}
            className="text-gray-500 hover:text-gray-300 transition-colors"
            aria-label="Close"
          >
            <X size={18} />
          </button>
        </div>

        {/* Body */}
        <div className="px-6 py-5 space-y-5 max-h-[70vh] overflow-y-auto">

          {/* What it is */}
          <section>
            <h3 className="text-gray-200 font-semibold text-sm mb-2">What is MarketLens?</h3>
            <p className="text-gray-400 text-sm leading-relaxed">
              MarketLens is a free, educational tool that overlays historical stock price
              charts with annotated market events — earnings reports, product launches,
              regulatory actions, and macro shocks — so you can understand <em>why</em> prices moved.
            </p>
          </section>

          {/* Data sources */}
          <section>
            <h3 className="text-gray-200 font-semibold text-sm mb-2">Data Sources</h3>
            <ul className="text-gray-400 text-sm space-y-1.5">
              <li className="flex gap-2">
                <span className="text-gray-600 mt-0.5">•</span>
                <span>
                  <span className="text-gray-300">Price history</span> — weekly closing prices
                  from Yahoo Finance, updated daily after market close.
                </span>
              </li>
              <li className="flex gap-2">
                <span className="text-gray-600 mt-0.5">•</span>
                <span>
                  <span className="text-gray-300">Events</span> — hand-curated by the MarketLens
                  team. Each event is selected based on measurable price impact (±5% or more).
                </span>
              </li>
              <li className="flex gap-2">
                <span className="text-gray-600 mt-0.5">•</span>
                <span>
                  <span className="text-gray-300">Live news</span> — headlines pulled from
                  Yahoo Finance RSS. May be temporarily unavailable.
                </span>
              </li>
              <li className="flex gap-2">
                <span className="text-gray-600 mt-0.5">•</span>
                <span>
                  <span className="text-gray-300">AI events</span> — generated by Claude
                  (Anthropic). Requires your own API key. Results are AI-generated and
                  may contain inaccuracies.
                </span>
              </li>
            </ul>
          </section>

          {/* Supported tickers */}
          <section>
            <h3 className="text-gray-200 font-semibold text-sm mb-2">Supported Tickers</h3>
            <div className="flex flex-wrap gap-1.5">
              {["NVDA","TSLA","AMZN","META","AAPL","MSFT","GOOGL","AMD","NFLX","JPM","BABA"].map((t) => (
                <span key={t} className="px-2 py-0.5 rounded-md bg-gray-800 text-gray-300 text-xs font-mono">
                  {t}
                </span>
              ))}
            </div>
          </section>

          {/* Disclaimer */}
          <section className="rounded-xl bg-amber-950/30 border border-amber-900/40 px-4 py-3">
            <h3 className="text-amber-400 font-semibold text-sm mb-1.5">Disclaimer</h3>
            <p className="text-amber-200/70 text-xs leading-relaxed">
              MarketLens is for <strong className="text-amber-200">educational and informational purposes only</strong>.
              Nothing on this site constitutes financial or investment advice.
              The Signal score is a heuristic rule, not a model prediction.
              Past price patterns do not guarantee future results.
              Always do your own research before making any investment decisions.
            </p>
          </section>

          {/* Source code */}
          <section>
            <a
              href="https://github.com/leijie-tao/Market-Lens"
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-1.5 text-xs text-blue-400 hover:text-blue-300 transition-colors"
            >
              <ExternalLink size={12} />
              View source on GitHub
            </a>
          </section>
        </div>
      </div>
    </div>
  );
}
